//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Contacto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contacto()
        {
            this.Entrega = new HashSet<Entrega>();
            this.Recepcion = new HashSet<Recepcion>();
        }
    
        public int ID_Contacto { get; set; }

        [StringLength(100, MinimumLength = 5)]
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Debe ingresar el nombre del contacto")]
        public string Nombre { get; set; }

        [StringLength(20, MinimumLength = 13)]
        [Display(Name = "No. DPI/CUI")]
        [Required(ErrorMessage = "Debe ingresar el documento de identificación del contacto")]
        public string CUI { get; set; }

        /*[RegularExpression(@"^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$",
            ErrorMessage = "El formato del correo es inválido.")]*/
        [EmailAddress]
        [StringLength(100)]
        [Display(Name = "Correo electrónico")]
        public string Correo { get; set; }

        [StringLength(10)]
        [Required(ErrorMessage = "Debe ingresar el gafete de identificación del contacto")]
        public string Gafete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrega> Entrega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Recepcion> Recepcion { get; set; }
    }
}
