//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.Entrega = new HashSet<Entrega>();
            this.Proveedor = new HashSet<Proveedor>();
            this.Oficina = new HashSet<Oficina>();
            this.RutaEntrega = new HashSet<RutaEntrega>();
        }
    
        public int ID_Empresa { get; set; }
        public int ID_Nivel { get; set; }

        [StringLength(50)]
        [Display(Name = "Nombre")]
        [Required(ErrorMessage = "Debe ingresar el nombre de la empresa")]
        public string Nombre { get; set; }

        [StringLength(20)]
        [Display(Name = "Tipo de empresa")]
        [Required(ErrorMessage = "Debe ingresar el tipo de empresa")]
        public string TipoEmpresa { get; set; }

        [StringLength(200)]
        [DataType(DataType.MultilineText)]
        public string Detalle { get; set; }

        [Phone]
        [StringLength(100)]
        [Display(Name = "Teléfono")]
        public string Telefono { get; set; }

        [EmailAddress]
        [StringLength(100)]
        [Display(Name = "Correo electrónico")]
        public string Correo { get; set; }
        public string PBX { get; set; }

        [StringLength(20, MinimumLength = 7)]
        [Display(Name = "NIT")]
        [Required(ErrorMessage = "Debe ingresar el documento de identificación de la empresa")]
        public string NIT { get; set; }

        [StringLength(20)]
        [Display(Name = "Encargado")]
        [Required(ErrorMessage = "Debe ingresar el nombre del encargado")]
        public string Encargado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entrega> Entrega { get; set; }
        public virtual Nivel Nivel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Proveedor> Proveedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Oficina> Oficina { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RutaEntrega> RutaEntrega { get; set; }
    }
}
