//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ERPMensajeriaEntities : DbContext
    {
        public ERPMensajeriaEntities()
            : base("name=ERPMensajeriaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contacto> Contacto { get; set; }
        public virtual DbSet<Edificio> Edificio { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Entrega> Entrega { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<Oficina> Oficina { get; set; }
        public virtual DbSet<Paquete> Paquete { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Recepcion> Recepcion { get; set; }
        public virtual DbSet<RutaEntrega> RutaEntrega { get; set; }
        public virtual DbSet<SolicitudProveedor> SolicitudProveedor { get; set; }
        public virtual DbSet<TipoUsuario> TipoUsuario { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
