//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paquete
    {
        public int ID_Paquete { get; set; }
        public int ID_SolicitudProveedor { get; set; }
        public string Descripcion { get; set; }
        public string Detalle { get; set; }
        public string Estado { get; set; }
        public string Extra { get; set; }
    
        public virtual SolicitudProveedor SolicitudProveedor { get; set; }
    }
}
