//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recepcion
    {
        public int ID_Recepcion { get; set; }
        public int ID_Contacto { get; set; }
        public int ID_Proveedor { get; set; }
        public string Tipo { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
