//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Recepcion
    {
        public int ID_Recepcion { get; set; }

        [DisplayName("Contacto")]
        [Required(ErrorMessage = "Debe seleccionar el contacto")]
        public int ID_Contacto { get; set; }

        [DisplayName("Proveedor")]
        [Required(ErrorMessage = "Debe seleccionar el proveedor")]
        public int ID_Proveedor { get; set; }

        [StringLength(7, MinimumLength = 6)]
        [Display(Name = "Tipo")]
        [Required(ErrorMessage = "Debe seleccionar el tipo")]
        public string Tipo { get; set; }
    
        public virtual Contacto Contacto { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
