//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RutaEntrega
    {
        public int ID_RutaEntrega { get; set; }
        public int ID_Empresa { get; set; }
        public int ID_Proveedor { get; set; }
        public string ORDEN { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
