//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP_Mensajeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudProveedor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudProveedor()
        {
            this.Paquete = new HashSet<Paquete>();
        }
    
        public int ID_SolicitudProveedor { get; set; }
        public int ID_Proveedor { get; set; }
        public System.DateTime Fecha_Ingreso { get; set; }
        public System.TimeSpan Hora_Ingreso { get; set; }
        public Nullable<System.DateTime> Fecha_Creacion { get; set; }
        public string Descripcion_Corta { get; set; }
        public string Elevador { get; set; }
        public string Estado_Entrega { get; set; }
        public string Entregado { get; set; }
        public string Aprobado { get; set; }
        public string Tipo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Paquete> Paquete { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
